language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
install:
- npm install
- npm run generate
script:
- echo "Skipping tests"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_ACCESS_TOKEN"
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master
env:
  global:
    secure: gg2e122ePNayoOidiMnFBQpr+OT7qIx/hb03LF2fa6gG0sYyOeIe5LzaM1Hl9ZFsEdB0i6wXBHDY7+zihxt1ikl8KaoApHRc1Qt50PDOWGChPl4SdZeuQNr97hnbp6mOnfkgcSjRNizfhqawmZauiqHCvl27nCwHDgUeDUKyflI=
