# Site settings
mainTitle: "Simon Dittlmann"
email: me@itnotes.de
description: "This blog is about it notes, lean development, DevOps and programing"
baseurl: ""
author: "Simon Dittlmann"
publisher: "Simon Dittlmann"
url: "https://www.itnotes.de"
twitter_username: SimonDittlmann
github_username:  Pindar

# Build settings
markdown: kramdown
permalink: pretty
paginate: 6

# Gems
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag
